version: '2'
services:
  metrics_collector:
    build: ./metrics_collector
    volumes:
      - ./metrics_collector/metrics_collector:/usr/src/metrics_collector/metrics_collector

  metrics_loader:
    build: ./metrics_loader
    volumes:
      - ./metrics_loader/metrics_loader:/usr/src/metrics_loader/metrics_loader
